name: subscription
description: Subscription - catering payment manager (debug scaffold)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  firebase_core: ^2.16.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.10.0
  firebase_storage: ^11.3.0
  firebase_messaging: ^14.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  razorpay_flutter: ^1.3.8
  image_picker: ^1.0.0
  connectivity_plus: ^4.0.1
  pdf: ^3.10.0
  printing: ^5.10.0
  flutter_local_notifications: ^12.0.5
  http: ^0.13.6
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/mockdata/sample_data.json
